fixtures:
  repositories:
    apt: 'git://github.com/puppetlabs/puppetlabs-apt'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    concat: 'git://github.com/puppetlabs/puppetlabs-concat'
    epel: 'https://github.com/stahnma/puppet-module-epel'
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
